wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: train/geopotential_500
      5: 1
      6:
      - 1
    - 1: train/temperature_850
      5: 1
      6:
      - 1
    - 1: train/loss
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: val/w_rmse_geopotential_500_day_3
      5: 1
      6:
      - 1
    - 1: val/w_rmse_temperature_850_day_3
      5: 1
      6:
      - 1
    - 1: val/acc_geopotential_500_day_3
      5: 1
      6:
      - 1
    - 1: val/acc_temperature_850_day_3
      5: 1
      6:
      - 1
    python_version: 3.10.4
    start_time: 1666247130.585582
    t:
      1:
      - 1
      - 9
      - 41
      - 49
      - 54
      - 55
      - 63
      2:
      - 1
      - 9
      - 41
      - 49
      - 54
      - 55
      - 63
      3:
      - 7
      - 13
      - 23
      4: 3.10.4
      5: 0.13.4
      8:
      - 1
      - 5
